#!/bin/sh
#
# fix-tb16-lan - fix network adapter problem with Dell TB16
#
# see https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1667750 for details
#
# (c) 2017 Dirk Moebius
#

sudo ethtool -s enp14s0u1u2 speed 100 duplex full autoneg on

