#!/usr/bin/bash

desktop=$(xdotool get_desktop)

for wid in `xdotool search --desktop $desktop --onlyvisible --name ""`
do
  name=$(xdotool getwindowname $wid)
  echo "Moving $wid: $name"
  eval $(xdotool getwindowgeometry --shell $wid)
  WIDTH=$((WIDTH > 1600 ? 1600 : WIDTH))
  HEIGHT=$((HEIGHT > 870 ? 870 : HEIGHT))
  # unmaximize first (maximized windows cannot be resized)
  wmctrl -i -r $wid -b remove,maximized_vert,maximized_horz
  # now resize and move
  xdotool windowsize $wid $WIDTH $HEIGHT windowmove $wid 0 30
done

